name: Issue Helper

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to run this action on'
        required: true
        type: integer
jobs:
  base:
    runs-on: ubuntu-latest
    outputs:
      parsed: ${{ steps.parse.outputs.payload }}
    steps:
      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.4
        with:
          issue_number: ${{ github.event_name == 'workflow_dispatch' && inputs.issue_number || github.event.issue.number }}
      - name: Annotate issue
        id: annotate
        uses: Glease/GTNHIssueHelper@latest
        with:
          formdata: ${{ steps.parse.outputs.payload }}
      - name: Post comment
        if: ${{ steps.annotate.outputs.comments != ''}}
        uses: KeisukeYamashita/create-comment@v1
        with:
          comment: ${{ steps.annotate.outputs.comments }}
        
